version: 2
all-policies: false
api-url: https://api.gitguardian.com
exit-zero: false
paths-ignore:
  - "**/README.md"
  - doc/*
  - LICENSE
  - .dockerignore
  - .gitignore
show-secrets: false
verbose: false
