# Options for analysis running.
run:
  timeout: 10m
  tests: false
  concurrency: 4

issues:
  exclude-dirs:
    - pkg/clinical/presentation/graph/

linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gosec
    - misspell
    - revive
    - funlen
    - gofmt
    - unparam
    - errorlint
    - bodyclose
    - gocritic
    - nilerr
    - ireturn
    - importas
    - wsl
    - exportloopref
    - nilerr
    - makezero
    - reassign

linters-settings:
  staticcheck:
    checks: ["all"]
  funlen:
    lines: -1
    statements: -1
  gosec:
    excludes:
      - G304
      - G101
  revive:
    rules:
      - name: unused-parameter
        severity: warning
        disabled: true
        arguments:
          - allowRegex: "^_"
